// Figma Shop / Customize / 390×882, 359:600 (HEAD) and 359:689 (PET).
export const accessories = [
  {
    id: "AviatorCap",
    name: "비행사 모자",
    category: "head",
    price: 520,
    image: "/assets/customize/AviatorCap.png",
  },
  {
    id: "RangerHat",
    name: "탐험가 모자",
    category: "head",
    price: 480,
    image: "/assets/customize/RangerHat.png",
  },
  {
    id: "TopHat",
    name: "실크햇",
    category: "head",
    price: 650,
    image: "/assets/customize/TopHat.png",
  },
  {
    id: "LeafBow",
    name: "나뭇잎 리본",
    category: "head",
    price: 280,
    image: "/assets/customize/LeafBow.png",
  },
  {
    id: "RoundGlasses",
    name: "둥근 안경",
    category: "head",
    price: 340,
    image: "/assets/customize/RoundGlasses.png",
  },
  {
    id: "PirateBandana",
    name: "해적 두건",
    category: "head",
    price: 430,
    image: "/assets/customize/PirateBandana.png",
  },
  {
    id: "FlowerCrown",
    name: "꽃 화관",
    category: "head",
    price: 560,
    image: "/assets/customize/FlowerCrown.png",
  },
  {
    id: "MushroomHat",
    name: "버섯 모자",
    category: "head",
    price: 390,
    image: "/assets/customize/MushroomHat.png",
  },
  {
    id: "ChefHat",
    name: "요리사 모자",
    category: "head",
    price: 420,
    image: "/assets/customize/ChefHat.png",
  },
  {
    id: "RibbonWig",
    name: "리본 가발",
    category: "head",
    price: 590,
    image: "/assets/customize/RibbonWig.png",
  },
  {
    id: "SquareGlasses",
    name: "사각 안경",
    category: "head",
    price: 360,
    image: "/assets/customize/SquareGlasses.png",
  },
  {
    id: "GreenBeanie",
    name: "초록 비니",
    category: "head",
    price: 410,
    image: "/assets/customize/GreenBeanie.png",
  },
  {
    id: "Monocle",
    name: "황금 단안경",
    category: "head",
    price: 760,
    image: "/assets/customize/Monocle.png",
  },
  {
    id: "JewelCrown",
    name: "보석 왕관",
    category: "head",
    price: 1200,
    image: "/assets/customize/JewelCrown.png",
  },
  {
    id: "Squirrel",
    name: "다람쥐 친구",
    category: "pet",
    price: 680,
    image: "/assets/customize/Squirrel.png",
  },
  {
    id: "PilotOwl",
    name: "파일럿 부엉이",
    category: "pet",
    price: 820,
    image: "/assets/customize/PilotOwl.png",
  },
  {
    id: "Chameleon",
    name: "카멜레온",
    category: "pet",
    price: 740,
    image: "/assets/customize/Chameleon.png",
  },
  {
    id: "FennecFox",
    name: "사막여우",
    category: "pet",
    price: 760,
    image: "/assets/customize/FennecFox.png",
  },
  {
    id: "WheelHamster",
    name: "쳇바퀴 햄스터",
    category: "pet",
    price: 700,
    image: "/assets/customize/WheelHamster.png",
  },
  {
    id: "Budgie",
    name: "앵무새",
    category: "pet",
    price: 620,
    image: "/assets/customize/Budgie.png",
  },
  {
    id: "ChefHedgehog",
    name: "요리사 고슴도치",
    category: "pet",
    price: 780,
    image: "/assets/customize/ChefHedgehog.png",
  },
  {
    id: "SugarGlider",
    name: "슈가글라이더",
    category: "pet",
    price: 850,
    image: "/assets/customize/SugarGlider.png",
  },
  {
    id: "SewingCat",
    name: "바느질 고양이",
    category: "pet",
    price: 880,
    image: "/assets/customize/SewingCat.png",
  },
  {
    id: "GalaxyTurtle",
    name: "은하 거북이",
    category: "pet",
    price: 1100,
    image: "/assets/customize/GalaxyTurtle.png",
  },
  {
    id: "DetectiveLizard",
    name: "탐정 도마뱀",
    category: "pet",
    price: 900,
    image: "/assets/customize/DetectiveLizard.png",
  },
  {
    id: "RoyalMouse",
    name: "왕관 생쥐",
    category: "pet",
    price: 980,
    image: "/assets/customize/RoyalMouse.png",
  },
] as const;
export type AccessoryId = (typeof accessories)[number]["id"];
