// Original Figma assets. Generated from the captured design context.
export const assets = {
  buff: {
    imgRectangle: "/assets/figma/buff-rectangle.png",
    imgRectangle1: "/assets/figma/buff-rectangle1.png",
    imgEllipse: "/assets/figma/buff-ellipse.svg",
  },
  dashboard: {
    imgAvatarFrame: "/assets/figma/dashboard-avatar-frame.png",
    imgDinoPortrait: "/assets/figma/dashboard-dino-portrait.png",
    imgNavigationItemHomePixelIcon: "/assets/figma/dashboard-navigation-item-home-pixel-icon.svg",
    imgNavigationItemQuestPixelIcon: "/assets/figma/dashboard-navigation-item-quest-pixel-icon.svg",
    imgNavigationItemDashboardPixelIcon:
      "/assets/figma/dashboard-navigation-item-dashboard-pixel-icon.svg",
    imgNavigationItemShopPixelIcon: "/assets/figma/dashboard-navigation-item-shop-pixel-icon.svg",
    imgStatusCameraDot: "/assets/figma/dashboard-status-camera-dot.svg",
  },
  dinosaur: {
    imgDinoSelectBackgroundPixelJungle:
      "/assets/figma/dinosaur-dino-select-background-pixel-jungle.png",
    imgDino: "/assets/figma/dinosaur-dino.png",
    imgDino1: "/assets/figma/dinosaur-dino1.png",
    imgDino2: "/assets/figma/dinosaur-dino2.png",
    imgDino3: "/assets/figma/dinosaur-dino3.png",
    imgDino4: "/assets/figma/dinosaur-dino4.png",
    imgDino5: "/assets/figma/dinosaur-dino5.png",
    imgEllipse: "/assets/figma/dinosaur-ellipse.svg",
  },
  "first-result": {
    imgRectangle: "/assets/figma/first-result-rectangle.png",
    imgRectangle1: "/assets/figma/first-result-rectangle1.png",
    imgEllipse: "/assets/figma/first-result-ellipse.svg",
  },
  home: {
    imgNavigationItemHomePixelIcon: "/assets/figma/home-navigation-item-home-pixel-icon.svg",
    imgNavigationItemQuestPixelIcon: "/assets/figma/home-navigation-item-quest-pixel-icon.svg",
    imgNavigationItemDashboardPixelIcon:
      "/assets/figma/home-navigation-item-dashboard-pixel-icon.svg",
    imgNavigationItemShopPixelIcon: "/assets/figma/home-navigation-item-shop-pixel-icon.svg",
    imgQuestItem0CheckboxIcon: "/assets/figma/home-quest-item0-checkbox-icon.svg",
    imgQuestItem0PixelIcon: "/assets/figma/home-quest-item0-pixel-icon.svg",
    imgQuestItem1PixelIcon: "/assets/figma/home-quest-item1-pixel-icon.svg",
    imgQuestItem2CheckboxIcon: "/assets/figma/home-quest-item2-checkbox-icon.svg",
    imgQuestItem2PixelIcon: "/assets/figma/home-quest-item2-pixel-icon.svg",
    imgQuestItem3PixelIcon: "/assets/figma/home-quest-item3-pixel-icon.svg",
    imgPixelIconIcon: "/assets/figma/home-pixel-icon-icon.svg",
    imgOpenChevron: "/assets/figma/home-open-chevron.svg",
    imgPixelIconRadar: "/assets/figma/home-pixel-icon-radar.svg",
    imgOpenChevron1: "/assets/figma/home-open-chevron1.svg",
    imgGroup: "/assets/figma/home-group.svg",
    imgFeedbackDinoMessage: "/assets/figma/home-feedback-dino-message.png",
    imgDinoPortrait: "/assets/figma/home-dino-portrait.png",
    imgDinoIdle: "/assets/figma/home-dino-idle.png",
    imgEnemyPixelMonster: "/assets/figma/home-enemy-pixel-monster.svg",
    imgFxImpactSprite: "/assets/figma/home-fx-impact-sprite.svg",
    imgHpBarPixelHeart: "/assets/figma/home-hp-bar-pixel-heart.svg",
    imgEllipse: "/assets/figma/home-ellipse.svg",
    imgEllipse1: "/assets/figma/home-ellipse1.svg",
    imgStageProgressGoalFlag: "/assets/figma/home-stage-progress-goal-flag.svg",
    imgStageProgressEggMarker: "/assets/figma/home-stage-progress-egg-marker.svg",
    imgAvatarFrame: "/assets/figma/home-avatar-frame.png",
    imgStatusCameraDot: "/assets/figma/home-status-camera-dot.svg",
  },
  login: {
    imgLoginBackgroundCanyonWaterfall: "/assets/figma/login-login-background-canyon-waterfall.png",
    imgLoginHeroRexRunBlackLogo: "/assets/figma/login-login-hero-rex-run-black-logo.png",
    imgLoginHeroRefinedEggSprite: "/assets/figma/login-login-hero-refined-egg-sprite.png",
    imgEllipse: "/assets/figma/login-ellipse.svg",
    imgLoginFormEmailIcon: "/assets/figma/login-login-form-email-icon.svg",
    imgLoginFormLockIcon: "/assets/figma/login-login-form-lock-icon.svg",
    imgLoginFormPasswordVisibility: "/assets/figma/login-login-form-password-visibility.svg",
  },
  "my-page": {
    imgEllipse: "/assets/figma/my-page-ellipse.svg",
    imgEllipse1: "/assets/figma/my-page-ellipse1.svg",
  },
  profile: {
    imgHealthBackgroundPixelOcean: "/assets/figma/profile-health-background-pixel-ocean.png",
    imgEllipse: "/assets/figma/profile-ellipse.svg",
    imgHealthFormPrivacyIcon: "/assets/figma/profile-health-form-privacy-icon.svg",
  },
  "quest-detail": {
    imgEllipse: "/assets/figma/quest-detail-ellipse.svg",
  },
  quests: {
    imgAvatarFrame: "/assets/figma/quests-avatar-frame.png",
    imgDinoPortrait: "/assets/figma/quests-dino-portrait.png",
    imgNavigationItemHomePixelIcon: "/assets/figma/quests-navigation-item-home-pixel-icon.svg",
    imgNavigationItemQuestPixelIcon: "/assets/figma/quests-navigation-item-quest-pixel-icon.svg",
    imgNavigationItemDashboardPixelIcon:
      "/assets/figma/quests-navigation-item-dashboard-pixel-icon.svg",
    imgNavigationItemShopPixelIcon: "/assets/figma/quests-navigation-item-shop-pixel-icon.svg",
    imgStatusCameraDot: "/assets/figma/quests-status-camera-dot.svg",
    imgDecorationRewardSpark: "/assets/figma/quests-decoration-reward-spark.svg",
  },
  reward: {
    imgRectangle: "/assets/figma/reward-rectangle.png",
    imgEllipse: "/assets/figma/reward-ellipse.svg",
    imgEllipse1: "/assets/figma/reward-ellipse1.svg",
  },
  risk: {
    imgEllipse: "/assets/figma/risk-ellipse.svg",
    imgFrame: "/assets/figma/risk-frame.svg",
    imgFrame1: "/assets/figma/risk-frame1.svg",
  },
  shop: {
    imgAvatarFrame: "/assets/figma/shop-avatar-frame.png",
    imgProductPhoto: "/assets/figma/shop-product-photo.png",
    imgProductPhoto1: "/assets/figma/shop-product-photo1.png",
    imgProductPhoto2: "/assets/figma/shop-product-photo2.png",
    imgProductPhoto3: "/assets/figma/shop-product-photo3.png",
    imgNavigationItemHomePixelIcon: "/assets/figma/shop-navigation-item-home-pixel-icon.svg",
    imgNavigationItemQuestPixelIcon: "/assets/figma/shop-navigation-item-quest-pixel-icon.svg",
    imgNavigationItemDashboardPixelIcon:
      "/assets/figma/shop-navigation-item-dashboard-pixel-icon.svg",
    imgNavigationItemShopPixelIcon: "/assets/figma/shop-navigation-item-shop-pixel-icon.svg",
    imgStatusCameraDot: "/assets/figma/shop-status-camera-dot.svg",
    imgDecorationRecommendationStar: "/assets/figma/shop-decoration-recommendation-star.svg",
    imgDecorationRrrCoin: "/assets/figma/shop-decoration-rrr-coin.svg",
    imgDecorationCustomizeSparkle: "/assets/figma/shop-decoration-customize-sparkle.svg",
  },
  withered: {
    imgRectangle: "/assets/figma/withered-rectangle.png",
    imgEllipse: "/assets/figma/withered-ellipse.svg",
  },
} as const;
